### ISSUE TITLE
JaegerMonkey information

### ISSUE THREAD

**Issue by mgaudet** [mgaudet/SpiderMonkeyBibliography#1]
Would love some good sources on JaegerMonkey.

**Comment by yozaam** [comment]
Is this the baseline compiler?

**Comment by mgaudet** [comment]
No, Baseline came later (and has never acquired a 'Monkey' name). 

[JaegerMonkey](https://wiki.mozilla.org/JaegerMonkey) was (as I understand it) the first Method JIT added to SpiderMonkey.
