### ISSUE TITLE
Add Compiler Compiler video series

### ISSUE THREAD

**Issue by mgaudet** [mgaudet/SpiderMonkeyBibliography#15]
https://www.youtube.com/playlist?list=PLo3w8EB99pqJVPhmYbYdInBvAGarDavh- 

(Is there a better URL?)

**Comment by mgaudet** [comment]
@codehag See above?

**Comment by codehag** [comment]
There used to be a better url...with the schedule. But it is down now. I need to figure that out.

There is this blog post that I wrote to give some more info: https://hacks.mozilla.org/2020/06/compiler-compiler-working-on-a-javascript-engine/

**Comment by mgaudet** [comment]
That's probably the right link to do for now; or some hybrid of that and youtube playlist. Will try to get that done sometime today. Thanks for the reply!
